"""payment sessions

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 14:47:42.077845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('order_reference', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='CREATED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('CREATED', 'PAID', 'EXPIRED', 'CANCELLED')", name='ck_payment_sessions_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_sessions_amount_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_sessions_merchant_created', 'payment_sessions', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_sessions_session_id'), 'payment_sessions', ['session_id'], unique=True)
    op.add_column('transactions', sa.Column('payment_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_payment_session_id'), 'transactions', ['payment_session_id'], unique=False)
    op.create_foreign_key('fk_transactions_payment_session', 'transactions', 'payment_sessions', ['payment_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_payment_session', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_payment_session_id'), table_name='transactions')
    op.drop_column('transactions', 'payment_session_id')
    op.drop_index(op.f('ix_payment_sessions_session_id'), table_name='payment_sessions')
    op.drop_index('ix_payment_sessions_merchant_created', table_name='payment_sessions')
    op.drop_table('payment_sessions')
    # ### end Alembic commands ###
